Repository andgein/SIStema, pull requests merged in 2018-03, with the labels that each got.

#379 Add Russian README
  README.md
  README.ru.md
Labels: review:easy

#373 Create CODEOWNERS
  src/CODEOWNERS
Labels: priority:4:ignore

#376 Upgrade dependencies
  src/requirements.txt
Labels: priority:1:high

#378 Make URL configs and middlewares work on Django 2.0
  src/web/frontend/urls.py
  src/web/modules/ejudge/admin.py
  src/web/modules/ejudge/school_urls.py
  src/web/modules/ejudge/urls.py
  src/web/modules/enrolled_scans/urls.py
  src/web/modules/entrance/staff/urls.py
  src/web/modules/entrance/templates/entrance/staff/check_user.html
  src/web/modules/entrance/templates/entrance/steps/confirm_profile.html
  src/web/modules/entrance/templates/entrance/steps/ensure_profile_is_full.html
  src/web/modules/entrance/urls.py
  src/web/modules/finance/urls.py
  src/web/modules/poldnev/urls.py
  src/web/modules/smartq/urls.py
  src/web/modules/study_results/school_urls.py
  src/web/modules/study_results/urls.py
  src/web/modules/topics/urls.py
  src/web/questionnaire/urls.py
  src/web/schools/middleware.py
  src/web/schools/urls.py
  src/web/sistema/settings.py
  src/web/sistema/templates/_staff_header.html
  src/web/sistema/templates/user_layout.html
  src/web/sistema/urls.py
  src/web/users/admin.py
  src/web/users/middleware.py
  src/web/users/urls.py
Labels: priority:1:high, review:easy, type:refactoring

#406 Fix type in migration
  src/web/questionnaire/migrations/0010_1_make_variant_orders_unique_20180302_2225.py
Labels: priority:4:ignore, type:refactoring

#408 Initial setup for codecov
  .coveragerc
  .travis.yml
  src/web/sistema/settings.py
Labels: group:devops, priority:2:medium, review:easy, type:feature

#414 Replace allow_tags with mark_safe for Django 2.0 support
  src/web/modules/ejudge/admin.py
  src/web/sistema/polymorphic.py
Labels: priority:3:low, review:easy, type:bug
