Repository andgein/SIStema, pull requests merged in 2018-04, with the labels that each got.

#430 Fix html issue on profile field's label
  src/web/users/forms/main.py
Labels: group:profile, review:easy, type:bug

#415 Remove for attribute from label with question title
  src/web/questionnaire/templates/questionnaire/blocks/question.html
  src/web/users/templates/users/profile.html
Labels: group:ux, priority:2:medium, review:easy, type:bug

#435 Disable vk widget animation
  src/web/sistema/templates/_vk_messages_widget.html
Labels: review:easy

#437 Add is_mandatory field to entrance task categories
  src/web/modules/entrance/migrations/0073_entranceexamtaskcategory_is_mandatory.py
  src/web/modules/entrance/models/main.py
  src/web/modules/entrance/models/steps.py
  src/web/modules/entrance/templates/entrance/steps/solve_exam.html
Labels: group:ux, priority:1:high, review:easy, type:feature

#442 Mark accepted but not fully solved tasks with yellow
  src/web/modules/entrance/models/main.py
  src/web/modules/entrance/staff/views.py
  src/web/modules/entrance/static/entrance/css/exam.css
  src/web/modules/entrance/templates/entrance/_exam_tasks_navigation.html
  src/web/modules/entrance/views.py
Labels: priority:2:medium, review:easy

#445 Reduce max file size for program task to match ejudge limit
  src/web/modules/entrance/forms.py
Labels: priority:3:low, review:easy

#452 Show previous submissions by file exam task
  src/web/modules/entrance/templates/entrance/staff/check_user.html
  src/web/modules/entrance/templates/entrance/staff/check_users_task.html
Labels: module:entrance, review:easy

#453 Update export
  src/web/modules/entrance/staff/export.py
Labels: priority:1:high, review:easy
